services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    # commandbus autowired
    Eventscase\MovieRental\Application\:
        resource: '../../src/Application/*'
        exclude: '../../src/Application/*/*/*{Query.php,Command.php}'
        tags:
            - { name: tactician.handler, typehints: true }
