doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Address:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/../../../config/doctrine/persistence/ValueObject'
                prefix: 'Eventscase\MovieRental\Domain\Shared\ValueObject'
                alias: Address
            Movie:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/../../../config/doctrine/persistence/Movie/Model'
                prefix: 'Eventscase\MovieRental\Domain\Movie\Model'
                alias: Movie
            Order:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/../../../config/doctrine/persistence/Order/Model'
                prefix: 'Eventscase\MovieRental\Domain\Order\Model'
                alias: Order
            OrderLine:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/../../../config/doctrine/persistence/Order/Model'
                prefix: 'Eventscase\MovieRental\Domain\Order\Model'
                alias: OrderLine
            User:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/../../../config/doctrine/persistence/User/Model'
                prefix: 'Eventscase\MovieRental\Domain\User\Model'
                alias: User
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true


