user_login:
  path: /login
  controller: Eventscase\MovieRental\Ui\Web\User\Controller\Security\SecurityController::login
  methods:  [POST, GET]

user_logout:
  path: /logout

rented_movies:
  path: /user/rented-movies
  controller: Eventscase\MovieRental\Ui\Web\User\Controller\RentedMoviesUserController::show
  methods: [GET]